### ISSUE TITLE
Towards Deeper Deep Reinforcement Learning

### ISSUE THREAD

**Issue by MarcoMeter** [nilsjohanbjorck/low-precision-rl#1]
Hi @nilsjohanbjorck !

I was not able to find another way to contact you regarding one of your latest papers. I've got a few questions on your paper "Towards Deeper Deep Reinforcement Learning", which was a very interesting read, so thank you for your contribution!

Figure 3 shows the behavior of the gradients during training ( log || grad loss || ). How did you extract/monitor these statistics? Did you take the magnitude of the output layer of your network or did you took the mean for every single layer?

Concerning spectral layer normalization, did you apply it to every layer of the critic?

Are you going to make your code open source?

Thanks
Marco

**Comment by nilsjohanbjorck** [comment]
for these questions, please email me on my Cornell email: njb225@cornell.edu!
