### ISSUE TITLE
Is there any advantage running all parts in fp16 over fp32+amp(NN part)?

### ISSUE THREAD

**Issue by LSC527** [nilsjohanbjorck/low-precision-rl#2]
It seems to me that most time is spend on training NN and interacting with environment. Using fp16 to train the NN part is enough.

**Comment by nilsjohanbjorck** [comment]
Naive mixed-precision does not work in my experience -- the culprit being some operations related to calculating the entropy. This is explained in the paper. However, amp is under active development so I can't say works/doesn't work right now -- but it should be simple to try it out!
